name: AccionDatabase
run-name: Accion de base de datos
on:
  push:
    branches: ["main"]
jobs:
  test-host:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
        - 32574:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - name: Verify MySQL connection from host
      run: |
        sudo apt-get install -y mysql-client
        mysql --host 127.0.0.1 --port 32574 -uroot -ppassword -e "SHOW DATABASES"
    - name: Jugando con las bases de datos
      run: |
        mysql -e "create database mibase; show databases; use mibase; create table mitabla(col1 varchar(25), col2 varchar(25)); insert into mitabla(col1, col2) values ('pepe', 'perez'); select * from mitabla;" 
