name: AccionDatabase
run-name: Accion de base de datos
on:
  push:
    branches: ["main"]
jobs:
  test-host:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
        - 32574:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - name: Verify MySQL connection from host
      run: |
        sudo apt-get install -y mysql-client
        mysql --host 127.0.0.1 --port 32574 -uroot -ppassword -e "SHOW DATABASES"
    - name: Creo una base de datos
      run: |
        mysql --host 127.0.0.1 --port 32574 -uroot -ppassword -e "create database mibase;"
    - name: Ya creada muestro todas las bases de datos
      run: |
        mysql --host 127.0.0.1 --port 32574 -uroot -ppassword -e "show databases;"
    - name: Voy a usar la base de datos que he creado y voy a crearle una tabla
      run: |
        mysql --host 127.0.0.1 --port 32574 -uroot -ppassword -e "use mibase; create table mitabla(col1 varchar(25), col2 varchar(25));"
    - name: Voy a usar la base de datos que he creado y e añado valores a la tabla
      run: |
        mysql --host 127.0.0.1 --port 32574 -uroot -ppassword -e "use mibase; insert into mitabla(col1, col2) values ('pepe', 'perez');"
    - name: Voy a usar la base de datos que he creado y y muestro los valores de mi tabla
      run: |
        mysql --host 127.0.0.1 --port 32574 -uroot -ppassword -e "use mibase; select * from mitabla;"
